---

- name: create default configuration for DHCP server (openrc)
  ansible.builtin.template:
    src: etc/conf.d/dhcpd.j2
    dest: /etc/conf.d/dhcpd
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart dhcp server
  when:
    - ansible_service_mgr | lower == "openrc"

- name: create DHCP server default
  ansible.builtin.template:
    src: etc/default/isc-dhcp-server.j2
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart dhcp server
  when:
    - ansible_os_family | lower == "debian"

- name: create config directory
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ dhcpd_main_config | dirname }}"
    owner: root
    group: root
    mode: 0755
  when:
    - dhcpd_main_config | dirname != "/etc"

- name: configure DHCP server
  become: true
  ansible.builtin.template:
    src: "etc/dhcp/dhcpd.conf.j2"
    dest: "{{ dhcpd_main_config }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - validate config
    - restart dhcp server

- name: flush handlers
  meta: flush_handlers

...
