---

- name: archlinux based
  block:
    - name: create default configuration for DHCP server (systemd)
      template:
        src: etc/dhcp/dhcp-server.conf.j2
        dest: /etc/dhcpd.conf
        owner: root
        group: root
        mode: 0644
        backup: true
        validate: dhcpd -t -cf %s
      notify:
        - restart dhcp server
      when:
        - ansible_service_mgr | lower == "systemd"

    - name: create default configuration for DHCP server (openrc)
      template:
        src: etc/conf.d/dhcp-server.j2
        dest: /etc/conf.d/dhcp-server
        owner: root
        group: root
        mode: 0644
        backup: true
      notify:
        - restart dhcp server
      when:
        - ansible_service_mgr | lower == "openrc"
  when:
    - ansible_distribution | lower == "archlinux"

- name: create DHCP server default
  template:
    src: etc/default/isc-dhcp-server.j2
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart dhcp server
  when:
    - ansible_os_family | lower == "debian"

- name: configure DHCP server
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: true
    # validate: dhcpd -t -cf %s
  loop:
    "{{ dhcpd_templates }}"
  notify:
    - validate config
    - restart dhcp server

...
