---

- name: include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yaml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yaml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yaml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yaml"
        - default.yaml
      skip: true

- name: python3-apt for debian
  when:
    - ansible_os_family | lower == 'debian'
  block:
    - name: make sure python3-apt is installed (only debian based)
      ansible.builtin.package:
        name:
          - python3-apt
        state: present
      register: _installed

    - name: update apt cache  # noqa no-handler
      when:
        - _installed.changed
      block:
        - name: clean apt cache  # noqa command-instead-of-module
          ansible.builtin.command: |
            apt-get clean
          register: apt_clean
          changed_when: apt_clean.rc != 0
          failed_when: apt_clean.rc != 0
          when: "ansible_version.full is version_compare('2.13', '<')"

        - name: clean apt cache
          ansible.builtin.apt:
            clean: true
          when: "ansible_version.full is version_compare('2.13', '>=')"

        - name: update package cache
          ansible.builtin.package:
            update_cache: true

- name: install requirements
  ansible.builtin.package:
    name: "{{ dhcpd_dependencies }}"
    state: present
  when:
    - dhcpd_dependencies | default([]) | count > 0

- name: get latest system information
  ansible.builtin.setup:

- name: merge dhcpd server configuration between defaults and custom
  ansible.builtin.set_fact:
    dhcpd_server_global: "{{ dhcpd_defaults_server_global | combine(dhcpd_server_global, recursive=True) }}"
    dhcpd_interfaces: "{{ dhcpd_defaults_interfaces | combine(dhcpd_interfaces, recursive=True) }}"
    dhcpd_subnets: "{{ dhcpd_defaults_subnets | combine(dhcpd_subnets, recursive=True) }}"
    dhcpd_groups: "{{ dhcpd_defaults_groups | combine(dhcpd_groups, recursive=True) }}"
    dhcpd_hosts: "{{ dhcpd_defaults_hosts | combine(dhcpd_hosts, recursive=True) }}"

...
