---

- name: include OS specific configuration
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yaml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yaml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yaml"
        - default.yaml
      skip: true

- block:
    - name: make sure python3-apt is installed (only debian based)
      package:
        name:
          - python3-apt
        state: present

    - name: clean apt cache
      command: apt-get clean
      args:
        warn: false
      register: apt_clean
      changed_when: apt_clean.rc != 0
      failed_when: apt_clean.rc != 0

  when:
    - ansible_os_family | lower == 'debian'

- name: get latest system information
  setup:

- name: update package cache
  package:
    update_cache: true


- name: install requirements
  package:
    name: "{{ dhcpd_dependencies }}"
    state: present

- name: merge dhcpd server configuration between defaults and custom
  set_fact:
    dhcpd_server_global: "{{ dhcpd_defaults_server_global |
      combine( dhcpd_server_global, recursive=True ) }}"

- name: update package cache
  package:
    update_cache: true

- name: get latest system information
  setup:

...
