---

- name: validate config
  ansible.builtin.command: |
    dhcpd -t -cf {{ dhcpd_main_config }}

- name: restart dhcp server
  ansible.builtin.service:
    name: "{{ dhcpd_service }}"
    state: restarted

...
