---

- name: validate config
  ansible.builtin.command: |
    dhcpd -t -cf /etc/dhcp/dhcpd.conf

- name: restart dhcp server
  ansible.builtin.service:
    name: "{{ dhcpd_service }}"
    state: restarted

...
